name: PR Content Check
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  id-token: write
concurrency:
  group: "pages-pr"
  cancel-in-progress: false
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Verify JSON integrity
        run: bun run verify

      - name: Check for violations
        run: |
          if [ -f "violations.json" ]; then
            echo "::error::JSON schema violations found. See violations.json for details."
            cat violations.json
            echo "violated=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Download Images and Update Hashes
        id: download
        run: bun run predeploy

      - name: Check for download failures
        run: |
          if [ -f "download_failures.txt" ]; then
            echo "::error::Some images failed to download. See download_failures.txt for details."
            cat download_failures.txt
            echo "failed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Check for failures
        if: always() # Run even if previous steps fail
        run: |
          has_failures=0
          if [ -f "download_failures.txt" ]; then
            has_failures=1
          fi
          if [ -f "violations.json" ]; then
            has_failures=1
          fi
          if [ "$has_failures" -eq 1 ]; then
            exit 1
          else
            echo "All downloads and JSON validations were successful!"
          fi 